AndroidTestRunner: make adb logcat -b crash non blocking
We only need a snapshot of the crash logs, so pass -d to make the call
non-blocking, this means we we can check right away for start/finish
of that process. This would also, the error:

  Error: failed to run ndk-stack command.
  agent:2024/10/21 16:31:42 build.go:404: QProcess: Destroyed while
process ("/opt/android/sdk/platform-tools/adb") is still running.

Change-Id: I2314d0b9567865934c2aa8f6d40ace2b4288ebb2
Reviewed-by: Ville Voutilainen <ville.voutilainen@qt.io>
(cherry picked from commit 2d3334a87955cd54bb47b57a25af2ed0ce6f3a69)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>